version: "3.7"

services:
  postfix:
    build:
      context: ./postfix
      args:
        - MYHOSTNAME=mail.wishmail.eu
        - MYDOMAIN=wishmail.eu
    ports:
      - "25:25"
      - "587:587"
    network_mode: "host"
    depends_on:
      - catchall-lmtp
    volumes:
      # map your certificate
      - ./postfix/assets:/etc/ssl/certs

  catchall-lmtp:
    build: ./catchall-lmtp
    ports:
      - "127.0.0.1:24:24"
    network_mode: "host"
    volumes:
      - ./catchall-lmtp/data:/data
    # Pass arguments to entrypoint.sh
    command: ["-p24", "-m", "/data/", "-f", "/data/prod_feed_config.yml"]

