--- # Mailbox configs
- username:  "user@domain"
  password:  "secret"
  protocol: "imap"
  host: "mail.mailserver.com"
  port:  993
- username:  "user@domain"
  password:  "secret"
  protocol: "imap"
  host: "mail.mailserver.com"
  port:  143
