* spamtrap-system's backend:

This is the source code for the processing backend of the distributed spamtrap-system, which is comprised of collectors - more specifically spamtraps (easily extended to server honeypots like dionaea) -, a [[https://www.mongodb.com/][MongoDB]] database and a reporting module. The asynchronous processing engine is the core of this system, which relies heavily on [[https://docs.python.org/3/library/asyncio.html][asyncio]].

The processing backend tokenizes, analyzes and classifies the incoming malspam. It uses the honeyclient [[https://github.com/buffer/thug][Thug]] for extraction of malware in download links and the malware analysis sandbox [[https://github.com/cuckoosandbox/cuckoo][Cuckoo]] further processing of the extracted binaries. The observed network connections during the execution of the samples as well as the malware configuration data containing command-and-control addresses found by [[https://github.com/JPCERTCC/MalConfScan][MalConfScan]] is extracted and used to map malware infrastructure, which will be presented in an [[https://www.elastic.co/elastic-stack][Elastic Stack]]

** Motivation
As already stated in [[file:../readme.org][spamtrap-system's readme]] *malspam* is one of the biggest cyberthreats. To the best of our knowledge there is no pipeline based on open source tool to analyze malspam samples and retrieve information about the network infrastructure used by the malware

The backend fulfills the tasks of persisting and analyzing collected malspam, while being decoupled from all collectors. It aims to streamline the process of extraction information on the network infrastructure used by the collected malware.
For collection refer to the directory [[../collectors/][collectors]], where the tools, which collect malspam are stored. ~maltrap~ itself receives those messages by using hpfeeds, persists those messages, processes and analyzes these date to finally report the results to an Elastic Stack and infer actionable threat intelligence.

** Architecture
The architecture is modular, the objects are passed around between the asynchronously running worker task with the help of queues. There are several components for ingesting the hpfeed, mediating the retrieved objects, processing and tokenization, enrichment and reporting. Those can flexibly extended, e.g. another processor could be added, which handles binary submissions of [[https://github.com/DinoTools/dionaea][Dionaea]] server honeypots or another reporter could be incorporated to report to MISP instance, too, and not only to an Elasticsearch instance.

*** Components
The processing backend consist of five components, which utilize subcomponents in turn for specialized task.

- [[file:processing_backend/feed/][FeedIngestor]]: Subscribes to hpfeeds-broker and receives hpfeeds-messages
- [[file:processing_backend/mediator.py][Mediator]]: Mediates data to process, enrich, store and report
- [[file:processing_backend/processor/][Processor]]: Tokenizes payloads, for each and every hpfeeds-channel a separate processor can be defined [fn:1]
- [[file:processing_backend/enricher/][Enricher]]: Performs enrichment, extracts further artifacts, and actual analysis (e.g. downloading file from URL, initiating detonation of malware in sandbox)
- [[file:processing_backend/reporter/][Reporter]]: Passes results to external plattform (e.g. Elasticsearch, MISP in future?)

Central element is the mediator, who is responsible for putting the objects on the right queues. Flexible parent-child-relationships could be built and each and every artifact can be handled and enriched on its own. E.g.: A received mail contains an URL, where an archive is hosted, which contains a malicious executable. The [[file:processing_backend/database/][DatabaseHandler]] is responsible for persisting data in the MongoDB, where each entity is stored in a separate collection (emails, files, urls, networkentities). This is accomplished by relying on [[https://github.com/mongodb/motor][Motor]], which is a non-blocking MongoDB driver for Python with asyncio.

*** Processing procedure
The following figure shows the building blocks and the single processing steps, which are actually performed asynchronously and happen therefore concurrently. The handing over of the data - the inter-task component communication so to say - is realized by using queues.

#+html: <p align="center" color="white"><img width="1000" src="../docs/img/spamtrap-backend.svg"></p>

The ingestor component subcribes to the specified hpfeeds-channel in order to receive spam-messages. If such a message is received, a FeedMsg is constructed and
passed to the Mediator. The Mediator is the central player, who controls the processing steps. The received message is at first persisted in its original form with the help of the DatabaseHandler, then it will be tokenized by the Processor-component. The tokenized result is passed to back to the Mediator again, which will put it on the queue for enriching, if needed. The Enricher component then triggers the analysis with Thug and/or Cuckoo. Thug is used by utilizing the Thug's Python API, the interaction with Cuckoo is accomplished by using its REST API [fn:2]. The Enricher receives and processes the results after analysis and passes them to the mediator. If the extracted artifact can be enriched further, it is placed on the enriching queue again, if it is fully enriched and should be reported, the mediator will pass it to the Reporter component by using the respective queue. The Reporter interacts with the enterprise search engine Elasticsearch and ingests the objects by using its REST API.

** Usage
The backend code offers only one commandline argument named ~--config~ to pass the path to a YAML-file, in which component and service configuration is bundled.
Given the interplay between the backend and its services, as well as the configuration choices, this seems to be the only reasonable choice.

#+begin_src bash
usage: run_backend.py [-h] [--config CONFIG_FILE]

Processing backend of spamtrap system. This component is able to subscribe to
hpfeeds-channel and receive messages in th eform of JSON files from there.
These messages will be persisted, further processed depending on the name of
the originating channel, enriched with the help of Thug and Cuckoo and
reported to an Elastic stack.

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG_FILE  A YAML-file, which is used to specify the components
			to run and services to contact.
#+end_src

The template file [[file:config/backend.yml.template][./config/backend.yml]] illustrates the mentioned configuration. To get a grasp of the options and services to configure, see the following section Configuration
Note, that it is important, that the services are actually avaiable, if the property ~enabled~ is set to true.

** Installation

*** Backend dependencies
To install the basic dependencies in the form of "normal" Python libraries inside a virtualenv follow the b/m steps:

#+begin_src bash
# Install virtualenv package
sudo pip3 install virtualenv

# Create virtualenv by specifying a specific interpreter
virtualenv -p /usr/bin/python3.8 backend_venv

# Activate newly created venv
source backend_venv/bin/activate

# Install the processing backends requirements
pip3 install -r ./requirements.txt

# Run it
python3.8 run_backend.py -h

# Deactivate venv
deactivate
#+end_src

In order to install [[https://github.com/buffer/thug][Thug]] some additional steps are needed, because it has further dependencies and the required [[https://github.com/area1/stpyv8][STPyV8]] has no package on Pypi. STPyV8 provides interoperability between Python3 and JavaScript running Google's V8 engine for Thug.

#+begin_src bash
# Basic build tools
sudo apt-get install python3 python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev

# Libfuzzy header files for ssdeep
sudo apt-get install libfuzzy-dev

# Graphviz header files
sudo  apt install graphviz-dev
sudo apt install libemu
sudo apt install libemu-dev

# Install thug inside venv
source backend_venv/bin/activate
pip3 install thug

# Retrieve and install stpyv8 inside venv
wget https://github.com/area1/stpyv8/releases/download/v8.8.278.6/stpyv8-8.8.278.6-cp38-cp38-linux_x86_64.whl
pip3 install stpyv8-8.8.278.6-cp38-cp38-linux_x86_64.whl
#+end_src

Note: Please choose the right version for your CPU architecture, OS and interpreter version from STPyV8's release page (https://github.com/area1/stpyv8/releases in order to be able to use the honeyclient thug.

** Configuration
The following sections deal with the modification of [[file:config/backend.yml.template][./config/backend.yml]] and the configuration of the (peripheral) services and configurable parameters of the backend itself.
Rename [[file:config/backend.yml.template][config/backend.yml.template]] and to ~config/backend.yml~ and pass it to ~run_backed.py~ via ~--config~, if you do not place it in the default location.

*** Gelocation data
First set to point to your IP-geolocation database. To be able to approximate IP-address to real world locations MaxMind's free geolocation data /GeoLite2/ is used [fn:3].

#+begin_src yaml
geo_db: ./GeoLite2-City.mmdb  # relative path to run_backend.py
#+end_src

*** Hpfeeds broker
For a list of potential brokers see https://hpfeeds.org/brokers. The usage of the GOlang implementation [[https://github.com/d1str0/HPFBroker][HPFBroker]] is recommended [fn:4].
Specify the credentials (in the hpfeeds lingo: ~ident~ and ~secret~) as well as the IP-address and port of the hpfeeds-broker. If you are using TLS, which is highly recommended (!), make sure to have a valid X.509-certificate [fn:5]. Specify the channel name and double check, that the broker is available.

#+begin_src yaml
ingesting:
  hpfeed:
    ident: reader
    secret: secret
    host: 127.0.0.1
    port: 10000
    tls: False

    channels:
      - spam.mails
      #- dionaea.capture
#+end_src

Specify the channel name. At the date of publishing only ~spam.mails~ is implemented. The processor-class used for messages received in this channel can handle RFC5322 data [fn:6]. Extending the functionaltity for other channel names and data formats is possible by subclassing [[file:processing_backend/processor/baseprocessor.py][baseprocessor.py]] and registering the channel name in the member variable ~channel~ of type tuple [fn:7].

Lastly double check, that the broker is available. You can do this by using the CLI tool like so:
#+begin_src bash
hpfeeds subscribe --tls --host feed.domain.tld -p 10000 -i "reader" -s "secret" -c "spam.mails
#+end_src

*** MongoDB
MongoDB as NoSQL-database is strictly required for using the spamtrap-system's backend and may be also used by Cuckoo and/or Thug. To spin up an instance, just run ~docker-compose up~ inside the directory [[file:/media/user01/data/Dropbox/study/masterthesis/lab/spamtrap-system/periphery/mongodb/][../periphery/mongodb]], which creates a MongoDB instance on localhost. If you prefer to run it in a VM or on a remote host, modify the following YAML-block inside [[file:config/backend.yml.template][./config/backend.yml]]:

#+begin_src yaml
persistance:
  mongodb:
    host: localhost
    port: 27017
    database_name: malspam
    indexttl: 10

  dumping:
    dump_files: True
    dump_path: ./dump # relative path to run_backend.py
#+end_src

In the section ~dumping~ you can specify, whether the incoming message should be dumped as files on disk in addition, if you have different use cases and just want to have file-artifacts.

*** Cuckoo
To install Cuckoo use the [[https://www.ansible.com/][Ansible]] role, which was developed to be able to install this malware analysis sandbox in a automated, fast and painless manner. See https://github.com/jgru/ansible-cuckoo-virtualbox for further information.

In order to be able to use Cuckoo, you have modify the configuration file. Specify the IP-address of the host running the Cuckoo REST API and the port number, on which it listens. Furtheron one can specify custom whitelists, which IPs and domain names, which are noise and should be therefore ignored.

#+begin_src yaml
enriching:
  enabled: True
  cuckoo:
    cuckoo_host: 10.0.0.12
    cuckoo_port: 8090
    cuckoo_timeout: 30
    whitelist_ips: ./config/whitelists/ip_whitelist.txt # relative path to run_backend.py
    whitelist_domains: ./config/whitelists/windows_services.txt # relative path to run_backend.py
#+end_src

See [[https://cuckoo.readthedocs.io/en/latest/installation/host/configuration/][Cuckoo's documentation]] on the optional customization of Cuckoo itselft.

*** Thug
Because Thug runs on the same box as the spamtrap-system's backend very little configuration has to be made. Just make sure, that the right Python interpreter (and the correct virtual environment, here ~backend_venv~ is used, where STPyV8 and the other dependencies of Thug were installed.

#+begin_src yaml
thug:
  # Modify thug.conf inside
  thug_config_dir: ./config/thug/ # relative path to run_backend.py
  thug_timeout: 25
  thug_interpreter: ./backend_venv/bin/python3.8 # relative path to run_backend.py
  whitelist_urls: ./config/whitelists/url_whitelist.txt # relative path to run_backend.py
#+end_src

Inside Thug's config directory is a file [[file:config/thug/thug.conf][./config/thug/thug.conf]], where you can specify, if and possibly which MongoDB to use to store the Thug's analysis results. See [[https://buffer.github.io/thug/doc/logging.html][Thug's documentation]] for more information on the configurable parameters.

*** Elasticsearch
The results can be pushed into an instance of the enterprise search engine Elasticsearch. To accomplish this set ~enabled~ to true and insert the hostname/IP-address and the corresponding port of the running Elasticsearch database. By setting ~relevant_documents~ one can specify, which artifacts should be jsonified and pushed into the given Elasticsearch instance.

#+begin_src yaml
reporting:
  enabled: True
  elasticsearch:
    host: 10.0.0.11
    port: 9200
    index: malspam
    relevant_documents: Email,File,Url,NetworkEntity
#+end_src

To deploy a dockerized ES use the ~docker-compose.yml~-file inside [[file:/media/user01/data/Dropbox/study/masterthesis/lab/spamtrap-system/periphery/elasticstack/][../periphery/elasticstack/]] and run ~docker-compose up~ inside this directory.

Note, that [[file:processing_backend/reporter/elastic_reporter.py][elastic_reporter.py]] creates an index, if it is not existent. The index mapping is specified within this file and could be altered there, if necessary.

* Footnotes

[fn:1] Inspired by JohnnyKV's https://github.com/johnnykv/mnemosyne.

[fn:2] Note, that both "external" analysis tools can store their results the same MongoDB instance.

[fn:3] See https://dev.maxmind.com/geoip/geoip2/geolite2/.

[fn:4] The Python implementation has a (unnecessary) restriction of 2KB message size (~MAXBUF = 1024**2~, see https://github.com/hpfeeds/hpfeeds/blob/master/hpfeeds/protocol.py).

[fn:5] /Let's encrypt/ is recommended https://letsencrypt.org/getting-started/.

[fn:6] See https://tools.ietf.org/html/rfc5322

[fn:7] I.e. handling binary data received from Dionaea server honeypots and transferred by hpfeeds is possible this way.
