* fosr-collector
This is a fork of [[https://github.com/waaeh/FakeOpenSmtpRelay][FakeOpenSMTPRelay]] created by [[https://github.com/waaeh/FakeOpenSmtpRelay][Waaeh]] [fn:1] to extend it to transport incoming mail to a [[https://hpfeeds.org/brokers][hpfeeds-broker]].

** Description
For a reference on the original tool see: https://github.com/waaeh/FakeOpenSmtpRelay/blob/master/README.md

*** Overview
FakeOpenSmtpRelay.py is a Python simulation of a working open SMTP relay. Waeeh's solution is based on the three building blocks:
- By utilizing the Python library [[https://github.com/aio-libs/aiosmtpd][aiosmtpd]] a fake open SMTP relay server is created, which will run on the SMTP ports: 25, 465 and587. It will accept any email from any sender.
- A dynamic rule engine is implemented, which tries to identify email probes from spammers and selectively relays them to their author. This script can be run in an automated way or with user-interaction. Safeguards are implemented to avoid turning into a true open relay in case of a logic flaw - such as the number of maximum emails relayed per day.
- The transport layer was extended by a [[https://hpfeeds.org/brokers][hpfeeds distributor]], so that spam message can be relayed to a [[https://hpfeeds.org/brokers][hpfeeds-broker]].

*** Added functionality
The threading model of the code was optimized, so that the SMTP servers listening on the different ports and offering different flavours of service (unencrypted, implicit and explicit TLS,...) run in the same event loop. Before every server instance run in its own thread using its on event loop, which counteracted the async concurrency model. Those server instance now add received emails to an async queue for further distribution. A commandline argument was added, so that a ~feed_config.yml~-file could be specified, which holds information about the message broker to use. The class ~HpfeedsDistributor~ was added and uses the a/m queue to retrieve incoming mails and send them to the backend in an authenticated and integrity protected manner in the form of a JSON-object, like so:

#+begin_src JSON
{
"sha256": "sha256_hexdigest",
"msg": "rfc5322_data_in_utf8"
}
#+end_src

** Dependencies
~fosr_collector.py~ requires in addition to the original dependencies the Python library [[https://github.com/hpfeeds/hpfeeds][hpfeeds]] in version 3.0.0.
Therefore it depends on the following libs:
- aiosmtpd==1.2.2
- atpublic==2.1.1
- dnspython==2.0.0
- hpfeeds==3.0.0

** Installation
Use Python package installer [[https://github.com/pypa/pip][pip]] to install the a/m requirements:

#+begin_src
pip3 install -r ./requirements.txt
#+end_src

Consider installing tho dependencies in a virtualenv like this

#+begin_src
# Install virtualenv package
sudo pip3 install virtualenv

# Create virtualenv by specifying a specific interpreter
virtualenv -p /usr/bin/python3.8 fosr_collector_venv

# Activate newly created venv
source fosr_collector_venv/bin/activate

# Install imap-collector's requirements
pip3 install -r ./requirements.txt

# Run it
python3.8 fosr_collector.py -h

# Deactivate venv
deactivate
#+end_src

** Usage
*** Commandline parameters
#+begin_src
usage: fosr_collector.py [-h] [-i] [-t] [-d] [-f FEED_CONFIG]

Simulates a Fake Open SMTP relay to collect spam mails.

optional arguments:
  -h, --help            show this help message and exit
  -i, --interactive
  -t, --testMode
  -d, --debug
  -f FEED_CONFIG, --feed-config FEED_CONFIG
			Config file in JSON-syntax specifying hpfeeds broker
			and credentials to use
#+end_src

*** TLS configuration for SMTP services
Create or reference certificate files to handle command STARTTLS and explicit TLS SMTP. The expected file names are hardcoded inside the code as ~INSTALL_CERTIFICATE_CERT_FILE~ & ~INSTALL_CERTIFICATE_KEY_FILE~. You can kust run ~openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.pem~ inside this directory.

*** Configuration for hpfeeds
~feed_config.yml~ stores the needed configuration for submitting mails to the [[https://hpfeeds.org/brokers][hpfeeds-broker]]

#+begin_src yaml
---  # Broker config
  broker: "127.0.0.1"
  port: 10_000
  identity: "writer"
  secret: "secret"
  channels:
    - "spam.mails"
#+end_src

** Footnotes

[fn:1] Released under the MIT license, which is compatible with GPL
