version: "2.4"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=es-docker
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4g

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    restart: always
    # depends_on:
    #   - elasticsearch
    mem_limit: 1g

networks:
  elk:
    driver: bridge
