version: '2'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb_data
        target: /bitnami/mongodb
        volume:
          nocopy: true
  
